// src/dataProcessing/nameMappings.js

const nameMappings = {
    "WizP": "WizP",
    "GetCrabby": "GetCrabby",
    "Omegam": "Omegam",
    "James Jr": "James Jr",
    "Cheunk": "Cheunk",
    "Fuji": "Fuji",
    "GLEN": "GLEN",
    "Grillindude": "Grillindude",
    "DSJ": "DSJ",
    "Rinzler": "Rinzler",
    "Kicks": "Kicks",
    "Jab": "Jab",
    "TsunamiGod77": "TsunamiGod77",
    "Owl": "Owl",
    "Neptune": "DayNeptune930",
    "DayNeptune930": "DayNeptune930",
    "moeznr": "moeznr",
    "Third Strongest": "Third Strongest",
    "Double": "Double",
    "Current": "Current",
    "honey!": "honey!",
    "NIKE": "NIKE",
    "CowboyDan": "CowboyDan",
    "meapz": "meapz",
    "Goomy": "Grillindude",
    "Jakan0id": "Jakan0id",
    "Haydes": "Haydes",
    "slug wife": "slug wife",
    "Farf": "Farf",
    "MothersDay": "MothersDay",
    "SpecialK": "SpecialK",
    "Neur0n": "GAYWIGGLE",
    "Jota Jota": "Jota Jota",
    "Fishbait": "Fishbait",
    "Slick": "Slick",
    "DD": "DayDream",
    "zapwad": "zapwad",
    "Bandit": "Bandit",
    "QBALLA": "QBALLA",
    "Golden Magikarp": "Golden Magikarp",
    "Rafael": "Rafael",
    "speedy": "speedy",
    "Pip": "Pip",
    "Nurz": "Nurz",
    "Bread": "Bread",
    "Sarahtonin": "Sarahtonin",
    "Conman": "Conman",
    "SodaCup": "SodaCup",
    "Wheels": "Wheels",
    "Silkylaroux": "Silkylaroux",
    "Daddison": "Daddison",
    "RemoRuby": "RemoRuby",
    "DayDream": "DayDream",
    "Inrenra": "Inrenra",
    "RaVen": "RaVen",
    "Noah": "Noah",
    "Tricolour": "Tricolour",
    "w0mp303": "w0mp",
    "Siegfried": "Siegfried",
    "escher": "escher",
    "Coffee": "Coffee",
    "Blankets": "Blankets",
    "Trent": "Trent",
    "EJL": "escher",
    "Glenlord Ghost": "GLEN",
    "Gingerham": "Gingerham",
    "Michael \"Kiefer\" Kiefer": "Michael D. Kiefer",
    "MP3": "MP3",
    "Hobbes": "Hobbes",
    "destinybond": "destinybond",
    "Tweeter": "Tweeter",
    "Bizz": "Bizz",
    "Smudge": "Smudge",
    "Ace?": "Ace?",
    "Michael D. Kiefer": "Michael D. Kiefer",
    "paprika": "paprika",
    "RNA Polymerase II": "RNA Polymerase II",
    "MaestrO": "MaestrO",
    "BIG PIKA": "BIG PIKA",
    "Loam": "Loam",
    "KoTo": "KoTo",
    "Sir+": "Sir+",
    "w0mp": "w0mp",
    "AceBox": "AceBox",
    "Secrets": "Secrets",
    "RAVN": "RAVN",
    "chozo": "chozo",
    "Namki": "Namki",
    "Neur0n with a zero": "GAYWIGGLE",
    "Miyagi": "Miyagi",
    "Mariposa": "Mariposa",
    "Kiefer": "Kiefer",
    "Gentle Kicks": "Gentle Kicks",
    "Zealot": "Zealot",
    "Walshy": "Walshy",
    "bearz": "bearz",
    "DJ": "DJ",
    "RIZ": "RIZ",
    "ZANE": "ZANE",
    "Butter Dog": "Butter Dog",
    "Veff": "Veff",
    "nj": "nj",
    "MetaRidKid": "MetaRidKid",
    "Speedy": "Speedy",
    "Nice Orbit": "Nice Orbit",
    "Mach1": "Mach1",
    "RICK": "RICK",
    "Safetyman": "Safetyman",
    "Crowken": "Crowken",
    "Troy": "Troy",
    "SweatyBurger": "SweatyBurger",
    "Venom": "Venom",
    "Tig": "Tig",
    "Ninjy": "Ninjy",
    "Datrooph": "Datrooph",
    "Jcorn": "Jcorn",
    "DDOG": "DDOG",
    "Lyric": "Lyric",
    "spliffy kong": "spliffy kong",
    "Spacejam": "Spacejam",
    "BEANz007": "BEANz007",
    "Fizzwiggle": "Fizzwiggle",
    "Doris": "Doris",
    "Dammut Bobbeh": "Dammut Bobbeh",
    "gnc": "gnc",
    "Jeeb": "Jeeb",
    "Zeal": "Zeal",
    "Pill Nye": "Pill Nye",
    "incelking": "incelking",
    "Suidt": "Suidt",
    "Oleyy": "Oleyy",
    "Blackwolf1738": "Blackwolf1738",
    "GetFoxy": "GetFoxy",
    "RanD": "RanD",
    "bizz": "bizz",
    "Squidner": "Squidner",
    "Shinji iCarly": "Shinji iCarly",
    "Fizz": "Fizz",
    "RINZLER": "Rinzler",
    "Marco": "Marco",
    "Clackers": "Clackers",
    "swid": "swid",
    "shwang": "shwang",
    "Fallen": "Fallen",
    "Agent 7": "Agent 7",
    "Biz": "Biz",
    "JNUS": "JNUS",
    "Rayquza": "Rayquza",
    "Skrad": "Skrad",
    "Ryan Charles Lanigan": "Ryan Charles Lanigan",
    "Paeve": "Paeve",
    "OmniOpal": "OmniOpal",
    "polear": "polear",
    "| Sayren": "| Sayren",
    "GAYWIGGLE": "GAYWIGGLE",
    "Wew Laddy": "Wew Laddy",
    "Elder": "Elder",
    "You": "You",
    "Slatty": "Slatty",
    "Mephistopheles": "Mephistopheles",
    "Cocoa": "Cocoa",
    "z29k": "z29k",
    "Yonky": "Yonky",
    "treyknows": "treyknows",
    "Mirror Mike": "Mirror Mike",
    "Hotdog \"Charles\" Chuck": "Hotdog \"Charles\" Chuck",
    "Bearz": "Bearz",
    "Welcomehouse": "Welcomehouse",
    "Rrob": "Rrob",
    "Doni": "Doni",
    "snatcher": "snatcher",
    "Zangoose": "Zangoose",
    "Hada": "Hada",
    "Isildur": "Isildur",
    "blorppppp": "blorppppp",
    "Jaimelopez": "Jaimelopez",
    "Mateo": "Mateo",
    "MarthBrooks": "MarthBrooks",
    "blackwolf": "blackwolf",
    "Nightsong": "Nightsong",
    "Glitch": "Glitch",
    "Quirk": "Quirk",
    "Roz": "Roz",
    "JGMatrix": "JGMatrix",
    "Asura": "Asura",
    "K-Ice": "K-Ice",
    "Moogle": "Moogle",
    "Z33T": "Z33T",
    "Cognition": "Cognition",
    "Grape": "Grape",
    "Big IF": "Big IF",
    "smokesignal": "smokesignal",
    "Zac": "Zac",
    "House": "House",
    "Elver": "Elver",
    "waddledoo": "waddledoo",
    "CBD": "CBD",
    "Chair": "Chair",
    "Phresh": "Phresh",
    "Burns": "Burns",
    "Douglas Jarles Falcon": "Douglas Jarles Falcon",
    "OguHD": "OguHD",
    "Mooj": "Mooj",
    "ElfmanShaggy": "ElfmanShaggy",
    "RNGesus": "RNGesus",
    "Slothbear": "Slothbear",
    "Shlapasaur": "Shlapasaur",
    "Rhett": "Rhett",
    "Grey": "Grey",
    "Mother's Day": "MothersDay",
    "Lynch": "Lynch",
    "BIG truck": "BIG truck",
    "Nik0": "Nik0",
    "Sen": "Sen",
    "Blobgi": "Blobgi",
    "Pibb": "Pibb",
    "james ahoy": "james ahoy",
    "JRoc": "JRoc",
    "Wew Lad": "Wew Lad",
    "LOG": "LOG",
    "bloom": "bloom",
    "spicychickensandwitch": "spicychickensandwitch",
    "Daniel": "Daniel",
    "Bam": "Bam",
    "ProudestOfTimes": "ProudestOfTimes",
    "Ans0nSmash": "Ans0nSmash",
    "SushiEater": "SushiEater",
    "dangitbobby": "dangitbobby",
    "Dang": "Dang",
    "dang": "dang",
    "Paul": "Paul",
    "Caenis": "Caenis",
    "Mirage": "Mirage",
    "collie": "collie",
    "HalfMyBones": "HalfMyBones",
    "Roach": "Roach",
    "brain lag": "brain lag",
    "Ferji": "Ferji",
    "FOVK": "FOVK",
    "PocketEllie": "PocketEllie",
    "Ovi": "Ovi",
    "hemorrhoid": "hemorrhoid"
  };
  
  module.exports = nameMappings;
  